// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/auth/signin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/signin">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/signin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/signup">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/membre/departement/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/membre/departement">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/membre/departement/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/membre/formations/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/membre/formations/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/membre/formations/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/membre/formations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/membre/formations">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/membre/formations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/membre/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/membre">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/membre/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/membre/profil/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/membre/profil">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/membre/profil/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/membre/resultats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/membre/resultats">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/membre/resultats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/responsable/departements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/responsable/departements">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/responsable/departements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/responsable/formations/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/responsable/formations/create">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/responsable/formations/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/responsable/formations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/responsable/formations">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/responsable/formations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/responsable/membres/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/responsable/membres">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/responsable/membres/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/responsable/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/responsable">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/responsable/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/test-vimeo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-vimeo">> = Specific
  const handler = {} as typeof import("../../../src/app/test-vimeo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/refresh">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/departements/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/departements/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/departements/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/departements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/departements">> = Specific
  const handler = {} as typeof import("../../../src/app/api/departements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/evaluation-results/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/evaluation-results/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/evaluation-results/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/evaluation-results/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/evaluation-results">> = Specific
  const handler = {} as typeof import("../../../src/app/api/evaluation-results/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/evaluations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/evaluations/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/evaluations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/evaluations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/evaluations">> = Specific
  const handler = {} as typeof import("../../../src/app/api/evaluations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/formations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/formations/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/formations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/formations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/formations">> = Specific
  const handler = {} as typeof import("../../../src/app/api/formations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users">> = Specific
  const handler = {} as typeof import("../../../src/app/api/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/videos/[id]/metadata/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/videos/[id]/metadata">> = Specific
  const handler = {} as typeof import("../../../src/app/api/videos/[id]/metadata/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/videos/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/videos/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/videos/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/videos/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/videos/upload">> = Specific
  const handler = {} as typeof import("../../../src/app/api/videos/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/dashboard/membre/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/membre">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/membre/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/responsable/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/responsable">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/responsable/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
